// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRuZuy1JlI-zNiQeL-ix2AeDU7SxGON0',
    appId: '1:26266490364:web:46d19fd6eb260a279f4e79',
    messagingSenderId: '26266490364',
    projectId: 'rapid-stream-460402-c3',
    authDomain: 'rapid-stream-460402-c3.firebaseapp.com',
    databaseURL: 'https://rapid-stream-460402-c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rapid-stream-460402-c3.firebasestorage.app',
    measurementId: 'G-CMDWYF0DFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASi5SBqz25uZAQCQbDR6nwmxSP1_ABa8c',
    appId: '1:26266490364:android:061145e33a6ad0449f4e79',
    messagingSenderId: '26266490364',
    projectId: 'rapid-stream-460402-c3',
    databaseURL: 'https://rapid-stream-460402-c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rapid-stream-460402-c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXBWOJ3nyP0w6L5Q9CvQHhyYRw2-v2Ms',
    appId: '1:26266490364:ios:60c049fb97f623e19f4e79',
    messagingSenderId: '26266490364',
    projectId: 'rapid-stream-460402-c3',
    databaseURL: 'https://rapid-stream-460402-c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rapid-stream-460402-c3.firebasestorage.app',
    iosBundleId: 'com.example.datn20242',
  );
}
